### ISSUE TITLE
On-screen keyboard issues

### ISSUE THREAD

**Issue by bddylol** [cherries-to/Cherry-Tree-TV#13]
Apon clicking the "Enter" or the "Tab" key it just writes out the word "Enter" or "Tab". I plan on fixing this either later tonight or sometime soon.

**Comment by datkat21** [comment]
when i was making the keyboard i added those keys and expected to give them functionality at some point but they literally just type out the character. it could be more useful to have those be actual keys (e.g. tab could be <code>\`</code> or <code>~</code> key and the enter could close the modal or make a newline so we can save on the confirm/cancel buttons at the bottom)

**Comment by datkat21** [comment]
One way you could address this keyboard issue is to make the buttons actually do something (looks kind of cursed without the confirm/cancel buttons on screen though)
![image](https://github.com/user-attachments/assets/02eaa28f-ea96-4d81-a78d-cd414a721a58)
