### ISSUE TITLE
Controller Status Bar not showing correct buttons.

### ISSUE THREAD

**Issue by tuckotb** [cherries-to/Cherry-Tree-TV#6]
On a generic Xbox controller, the related buttons aren't showing correctly and display weirdly.
![image](https://github.com/user-attachments/assets/7ee0352b-7229-4b87-a6a3-25966aa1bf98)

**Comment by datkat21** [comment]
This will most likely be fixed with the controller input overhaul coming later, but I can't fix that right now

**Comment by datkat21** [comment]
What does the controller show up as in the notification? Most of the generic controller types don't have icons yet and (could) be replaced by generic Xbox-like buttons if we need icons for them

**Comment by tuckotb** [comment]
It shows up as "Xbox Controller"

**Comment by tuckotb** [comment]
It seems like the issue has been fixed in fbac86e
